---
- name: Download docker binaries
  get_url:
    url: "{{ docker_download_url }}"
    dest: "/usr/local/src"
  become: true

- name: Unpack docker binaries
  unarchive:
    copy: no
    src: "/usr/local/src/{{ docker_package_file }}"
    dest: "/usr/local/src/"
    creates: "/local/src/docker/docker"
  become: true

- name: Copying docker binaries
  copy:
    remote_src: true
    src: "/usr/local/src/docker/{{ item }}"
    dest: /usr/bin
    mode: 0755
  with_items:
    - dockerd
    - docker
    - docker-containerd
    - docker-containerd-ctr
    - docker-containerd-shim
    - docker-runc
  become: true

- name: Add docker systemd unit file
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0644
  become: true
  register: systemd

- name: Reload systemd
  command: systemctl daemon-reload
  become: true
  when: systemd.changed

- name: Restart service
  service:
    name: docker
    state: restarted
    enabled: yes
  become: true
  when: systemd.changed
